ARG VERSION

FROM ghcr.io/riverlane/image-artiq-nix:${VERSION}

RUN nix-shell -I artiqSrc=/artiq nix-scripts/artiq-fast/shell-dev.nix

CMD ["nix-shell", "-I", "artiqSrc=/artiq", "/nix-scripts/artiq-fast/shell-dev.nix"]

